#!/bin/sh -e
cd ..
./setup
cd test

do_variant() {
	rm -rf "build_$1"
	meson setup "build_$1" --cross-file "$1" ; meson compile -C "build_$1"
}

#do_variant ivt_wx32_nostl
#do_variant ivt_wx32_staticstl
#do_variant ivt_wx64_nostl
#do_variant ivt_wx64_staticstl

do_variant ivt_lgx32_stl_scout
