#!/bin/sh -e

ITSETUP_DIR="`readlink -e "$0"`"
export ITSETUP_DIR="`dirname $ITSETUP_DIR`"

setupcore_build() {
	meson setup --reconfigure "$ITSETUP_DIR/build" "$ITSETUP_DIR"
	meson compile -C "$ITSETUP_DIR/build"
}

setupcore_build > "$ITSETUP_DIR/setupcore_build.log" || (echo "Error during ivorytower setup:" ; cat "$ITSETUP_DIR/setupcore_build.log" ; exit 1)

exec "$ITSETUP_DIR/build/setupcore" "$@"
