# Meson build file for notvcrt.
# This lets notvcrt be cleanly built using the bootstrap compilation environment.

project('notvcrt', 'c', 'cpp')

notvcrt_lib = static_library('notvcrt',
	'crt0_common.c',
	'crt0_dll.c',
	'crt0_dll_nomain.c',
	'crt0_exe_con.c',
	'crt0_exe_gui.c',
	'crt0_exe_con_w.c',
	'crt0_exe_gui_w.c',
	'crt0_fltused.c',
	'crt0_gs.c',
	'vcr_del01.cpp',
	'vcr_del02.cpp',
	'vcr_del03.cpp',
	'vcr_del04.cpp',
	'vcr_del05.cpp',
	'vcr_del06.cpp',
	'vcr_del07.cpp',
	'vcr_del08.cpp',
	'vcr_del09.cpp',
	'vcr_del10.cpp',
	'vcr_del11.cpp',
	'vcr_del12.cpp',
	'vcr_new1.cpp',
	'vcr_new2.cpp',
	'vcr_new3.cpp',
	'vcr_new4.cpp',
	'vcr_new5.cpp',
	'vcr_new6.cpp',
	'vcr_new7.cpp',
	'vcr_new8.cpp',
	'vcr_new_nothrow.cpp',
	'vcr_typeinfo.cpp'
)
